export const AUTHENTICATION_REQUEST="AUTHETICATION_REQUEST";
export const AUTHENTICATION_SUCCESS="AUTHETICATION_SUCCESS";
export const AUTHENTICATION_FAILURE="AUTHETICATION_FAILURE";

export const LOGOUT_REQUEST="LOGOUT_REQUEST";
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const LOGOUT_FAILURE="LOGOUT_FAILURE";

export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGGIN_FAILURE="LOGIN_FAILURE";
